dbs:
  - dummy:
      prompts: ... #path
      url: ... #unused
      skills: ...
      schema: ...
models:
  - dummy:
      responses:
        - |
          ```
          3
          ```
questionsPath: ...
exampleCounts:
  - 0
  - 1
  - 3
maxRetryCounts:
  - 0
  - 2
  - 4
