dbs:
  - dummy:
      prompts: data/dummy
      url: unused
      skills: data/dummy/skills
      schema: data/dummy/schema.txt
models:
  - dummy:
      repeat: true
      responses:
        - |
          Here is the query:
          ```
          3
          ```
        - |
          Here is the query:
          ```
          4
          ```
        - The answer is three.
questionsPath: data/questions.json
exampleCounts:
  - 0
  - 1
  - 3
maxRetryCounts:
  - 0
  - 2
  - 4
