dbs:
  - sql:
      prompts: ... #path
      url: ...
      auth: ...
      skills: ...
      schema: ...
  - neo4j:
      prompts: ... #path
      url: ...
      auth: ...
      skills: ...
      schema: ...
  - typedb:
      prompts: ... #path
      url: ...
      auth: ...
      skills: ...
      schema: ...
models:
  - dummy:
      responses:
        - |
          ```
          3
          ```
questionsPath: ...
exampleCounts:
  - 0
  - 1
  - 3
maxRetryCounts:
  - 0
  - 2
  - 4
