#!/usr/bin/env python3
"""Render a questions JSON as readable Markdown for review.

Reference queries are stored as single-line strings so the JSON stays diffable,
which makes them near-unreadable. This breaks them across lines at clause
boundaries and indents by parenthesis depth, so a reviewer can actually check
the joins.

Usage: format_questions.py [questions.json] [out.md]
"""

import json
import pathlib
import re
import sys

# Clause keywords that start a new line. Longest-first so "GROUP BY" wins over
# "GROUP", and "LEFT JOIN" over "JOIN".
BREAK = [
    "WITH RECURSIVE", "UNION ALL", "GROUP BY", "ORDER BY", "LEFT JOIN",
    "INNER JOIN", "CROSS JOIN", "UNION", "SELECT", "FROM", "WHERE", "HAVING",
    "LIMIT", "JOIN", "AND", "OR",
]
BREAK_RE = re.compile(r"(?<![A-Za-z0-9_])(" + "|".join(BREAK) + r")(?![A-Za-z0-9_])")
INDENT = "    "


# ", <name> AS (" starts the next CTE and deserves its own line.
NEXT_CTE_RE = re.compile(r"\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s+AS\s*\(", re.I)


def format_sql(sql: str) -> str:
    """Break a one-line query at clause boundaries, indenting by paren depth.

    Parentheses are never broken on: doing so splits `COUNT(*)` across lines.
    They only move the indent level, so subquery bodies sit one step in while
    function arguments stay put.
    """
    out, line, depth, i = [], "", 0, 0
    # Indent is decided by the depth the line STARTED at, so a line that closes
    # a CTE stays aligned with the rest of that CTE's body instead of dedenting.
    line_depth = 0

    def flush() -> None:
        nonlocal line
        if line.strip():
            out.append(INDENT * line_depth + " ".join(line.split()))
        line = ""

    while i < len(sql):
        # A new CTE: close off the previous one and start fresh at depth 0.
        m = NEXT_CTE_RE.match(sql, i) if depth == 0 else None
        if m:
            line += ","
            flush()
            line_depth = 0
            line = f"{m.group(1)} AS ("
            depth = 1
            i = m.end()
            continue
        ch = sql[i]
        if ch == "(":
            depth += 1
            line += ch
            i += 1
            continue
        if ch == ")":
            depth = max(0, depth - 1)
            line += ch
            i += 1
            continue
        m = BREAK_RE.match(sql, i)
        if m:
            flush()
            line_depth = depth
            line = m.group(1)
            i = m.end()
            continue
        line += ch
        i += 1
    flush()
    return "\n".join(out)


def main() -> None:
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "data/reactome/questions.json")
    dst = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else src.with_suffix(".md"))
    questions = json.loads(src.read_text(encoding="utf8"))["questions"]

    lines = [f"# {src.name} — {len(questions)} questions", ""]
    lines += ["Generated by `analysis/format_questions.py`; edit the JSON, not this file.", ""]
    for n, q in enumerate(questions, 1):
        lines.append(f"## {n}. {q['difficulty']}")
        lines.append("")
        lines.append(q["question"])
        lines.append("")
        if q.get("unanswerable"):
            lines += ["**Unanswerable** — the only correct response is the UNANSWERABLE token.", ""]
            continue
        shape = "ordered list" if q.get("ordered") else type(q["expected"]).__name__
        lines.append(f"**Expected** ({shape}):")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(q["expected"], indent=2, ensure_ascii=False))
        lines.append("```")
        lines.append("")
        for lang, sql in sorted(q.get("queries", {}).items()):
            lines.append(f"**{lang}**")
            lines.append("")
            lines.append("```sql")
            lines.append(format_sql(sql))
            lines.append("```")
            lines.append("")
    dst.write_text("\n".join(lines) + "\n", encoding="utf8")
    print(f"wrote {dst} ({len(questions)} questions)")


if __name__ == "__main__":
    main()
